### ISSUE TITLE
Snow not melting

### ISSUE THREAD

**Issue by wharris912** [Snownee/SnowRealMagic#265]
### Mod loader

Forge

### Minecraft version

1.19.3

### Mod version

7.2.0

### Modloader version

Forge

### If bug:

- [ ] Can you reproduce this issue with relevant mods only?

### Issue description

For some reason, the snow does not melt when it is concurrent with grass, tall grass, flowers, or saplings. I have the Serene Seasons mods installed as well. Yet, even in the summertime, the snow stays in those areas. Do you know if this is a bug? I have snowmelt enabled in the config files, too.

**Comment by Aceplante** [comment]
How are you even playing lol it crashes for me

**Comment by AnImpossibility** [comment]
I'm having the same problem, and I'm also using the fabric seasons mod (I think you're using the forge counterpart). For me, it only happens when the snow accumulates to a full 8 layers. Then, when it stops snowing or it turns to spring, the blocks that have plants and 8 layers of snow don't melt. I attached pictures below.
![2023-03-10_17 05 13](https://user-images.githubusercontent.com/105756699/224437045-92dad2a8-46e1-4514-83bf-a49887984e2b.png)
