### ISSUE TITLE
1.19.2 launcher starting crash "exit code 1"

### ISSUE THREAD

**Issue by matzar24h** [Snownee/SnowRealMagic#288]
### Mod loader

Forge

### Minecraft version

1.19.2

### Mod version

I tried using 7 ver. of this mod from 6.5.0 to 5.0.3

### Modloader version

43.2.0 recomended 1.19.2

### Modpack info

multiple mods like rubidium related, farming, mobs, structures, 2 dimensions, + many small funcionalities mods, 

### If bug:

- [ ] Can you reproduce this issue with relevant mods only?

### Issue description

When launching launcher, after a about 10 seconds i got error exit code 1. I tried few different versions of this mod from 1.19.2, but always the same...
All the mods work, only when adding magicsnow, launcher is crashing at start.

**Comment by Barerock** [comment]
Same thing with my install, and we both have Kiwi I assume?

**Comment by matzar24** [comment]
Well, I didn't read mod page first statement - "1.14+: Requires Kiwi".
Well, now everything is solved, no exit code crash.
But it's just because some mods didnt tell what library they require and most simple method it's just install all mods I want and than look in forge menu what libraries lacks in modpack.
This is first mod to see crash bc it's lacks library.

**Comment by matzar24** [comment]
Launcher starts up solved, but entering world now crashes. 
Didnt have time for that back then, so I'm opened today another Issue on github.
