### ISSUE TITLE
Creatures not spawning in snowy biomes

### ISSUE THREAD

**Issue by linkovich2** [Snownee/SnowRealMagic#297]
### Mod loader

Forge

### Minecraft version

1.19.2

### Mod version

6.5.1

### Modloader version

Forge 43.2.14

### If bug:

- [X] Can you reproduce this issue with relevant mods only?

### If bug: The latest.log file

https://pastebin.com/Gm1Z99bp

### Issue description

Ok, sorry this took so long but I wanted to be sure it was an issue with the mod before I sent anything. I've tested pretty extensively at this point, and can confirm that _monsters_ do spawn correctly in snowy biomes, but _creatures_ are exceedingly rare compared to vanilla. This issue becomes more pronounced if you stack another mod that adds snowy spawns on top, like Alex's Mobs, but it can be seen in vanilla (even though rabbits/polar bears are already pretty rare).

In flying around with _just_ kiwi and snow real magic for about a half hour, I saw only 1 rabbit in my snowy biomes and 1 polar bear (that spawned on ice). In vanilla in the same time, several groups of rabbits, goats, polar bears, etc.

I looked around in the source and cannot really tell what might be affecting these kinds of spawns in particular. But I've seen this enough in my testing to know its being caused by this. Also tested with just Kiwi and can confirm that it's not Kiwi, it's definitely specific to Snow Real Magic

**Comment by raffle2** [comment]
I just spent the entire day trying to figure out why alex mobs weren't spawning in their snowy biomes, and I also finally reached the same conclusion, the moment I turned off this mod, the mobs started spawning again. Huge relief that I'm not the only one facing this issue but also sad because I love this mod. I'm also on 1.19.2 using `SnowRealMagic-1.19.2-forge-6.5.1.jar` on Forge 43.2.0

**Comment by Snownee** [comment]
comment below if the problem persists
