### ISSUE TITLE
Snow doesn't generate in winter on otherwise rainy biomes with Serene Seasons

### ISSUE THREAD

**Issue by VindSole** [Snownee/SnowRealMagic#379]
### Mod loader

Fabric

### Minecraft version

1.21

### Mod version

11.0.1

### Modloader version

Fabric Loader 0.15.11, Fabric API 0.100.4

### [IMPORTANT] If bug:

- [X] I have confirmed this bug is reproducible on a minimal setup, not a modpack with many other mods.

### [IMPORTANT] If bug: The **latest.log** file, not the crash report

[https://gist.github.com/VindSole/f26ba0cc818c42551cf7163651ae132a.js"](https://gist.github.com/VindSole/f26ba0cc818c42551cf7163651ae132a)

### Issue description

On snowy biomes snow generates fine, but biomes on which it can start snowing instead of raining in cold seasons like winter, snow doesn't generate when using Serene Seasons alongside this mod.

![image](https://github.com/Snownee/SnowRealMagic/assets/63668266/6080685a-e20a-4067-910c-f60eb1d58d77)

**Comment by DavieRamble** [comment]
Hi,

I don't have experience with modding Minecraft, but it seems to me that the issue lies within the following function:

https://github.com/Snownee/SnowRealMagic/blob/fb2050a56cc420436f678f454cb220423e502715/src/main/java/snownee/snow/util/CommonProxy.java#L87

Here is what I changed:


```
public static boolean coldEnoughToSnow(Level level, BlockPos pos, Holder<Biome> biome) {
    return SeasonHooks.coldEnoughToSnowSeasonal(level, pos); <-- what I changed to
    // return biome.value().coldEnoughToSnow(pos); <-- default return value
}
```
> I'm not familiar with how mixins, dependencies, and other modding mechanics work in this context, so I added the dependency on the mod and created the function to directly call SereneSeasons.

Additionally, I'm not sure if this function does anything, because it returned false, but I changed it too:

https://github.com/Snownee/SnowRealMagic/blob/fb2050a56cc420436f678f454cb220423e502715/src/main/java/snownee/snow/util/CommonProxy.java#L91
```
public static boolean isWinter(Level level, BlockPos pos, Holder<Biome> biome) {
    ISeasonState seasonState = SeasonHelper.getSeasonState(level);
    return seasonState.getSeason().equals(Season.WINTER);
    // return false; <-- default return value
}
```

It appears that Serene Seasons does not override the original coldEnoughToSnow method, leading SnowRealMagic to use the value from vanilla Minecraft. However, this is just my initial assessment; I might be mistaken as I haven't tested this thoroughly.

![image](https://github.com/Snownee/SnowRealMagic/assets/123296930/0fbd460d-4628-4db2-ad52-306634f13e2b)

**Comment by FadedBoom** [comment]
Im sorry to ask i dumb question im new but how do i change the mod to use the code you did?
