### ISSUE TITLE
Support For Foliage From Other Mods

### ISSUE THREAD

**Issue by AshyAspen** [Snownee/SnowRealMagic#57]
Snow doesn't fill up on grass from Biomes O Plenty, berry bushes from Biomes O Plenty, etc.

If I'm not mistaken, it seems to be that the snow simply renders into these blocks instead of an actual change to the blocks themselves for the grass (maybe I'm wrong here) perhaps a config could be added to allow other blocks (such as "short grass" or "medium grass" in BOP) to render in with snow when snow is on a block next to them, or another way of supporting them.

Either way, support for modded blocks at (at least popular ones) would be really nice, even if we had to specify the blocks in a config file or it's just for foliage or something.

_Edit (If Needed):_ **Minecraft Forge 1.12.2-14.23.5.2847
Mod Version 0.3.3
Biomes O Plenty 7.0.1.2441**

**Comment by Snownee** [comment]
Hello, I have added block tag support in the latest version. You can send me the block IDs that should be able to be covered with snow. But since there is a bug that tags will fail to parse if there are non-exist IDs in json, support for other mods is going to be possible until 1.16 (because Mojang has fixed it)

**Comment by pimalel233** [comment]
Hi @Snownee , will that tag support only on 1.15? When I saw this issue got closed I  though it would get implemented in 1.12 as it was reported on that version. Is there any chance a backport of this feature will happen?

**Comment by Snownee** [comment]
@pimalel233  1.12.2 is no longer maintained
