### ISSUE TITLE
New Snow System

### ISSUE THREAD

**Issue by Matthysse** [Snownee/SnowRealMagic#66]
Hello!
I think the way the snow can be placed on stairs/slabs/walls/fences is not a good solution.
For example, if we remove the Snow real magic mod from a world where it already snowed on our house, our roofs will disappear. It's not good for mod-compatibility as you add for every slab a snowy variant which creates another block. 

My solution is like the snow works on vanilla minecraft (the snow layers are on top of the block) to make the snow not create a new block when placed on slabs for example, but a new model of the snow, which is 8 pixels lower, would fit on the slab without creating a new one. So it would work for every slab that exists with the tag "slab" because this new snow model would only appear on slabs. I don't know if it's clear, but I have the example of the mod called "Shifted Snow" for 1.10.2 which did exactly that. https://www.curseforge.com/minecraft/mc-mods/shiftedsnow

**Comment by Snownee** [comment]
Hello. First thank you for letting me know that mod. Are you sure you can retain the origin blocks if Shifted Snow get removed. I think that is impossible too because I just did some research to that mod and get the answer is no.

But I am willing to add a method for player who want their origin blocks back
